name: 'Environment selection'

on:
  push:
  workflow_call:


jobs:
  check_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Action
        id: check
        uses: ./
        with:
          deploy_unit: 'front'

      - name: Post Action
        run: |
          echo "environment=${{ steps.check.outputs.environment }}"
          echo "key=${{ steps.check.outputs.key }}"
          echo "unit=${{ steps.check.outputs.unit }}"
